Aggregate swap history
jetstreamgg/helipad pull request #89
Opened 2023-08-14 22:07 UTC by iceanddust

### What does this PR do?
It groups multi-hop swaps into a single swap object

2023-08-15 21:27 UTC, iceanddust commented on packages/hooks/src/swap/useSwapHistory.tsx
> +              token1: toToken?.token
Done, changed them to `fromAmount`, `fromToken`, `toAmount` and `toToken` in both hook responses to represent more precisely which is the origin and which is the target token

2023-08-16 00:53 UTC, inclinedmind commented on packages/hooks/src/swap/useSwapHistory.tsx
> +              token1: toToken?.token
thanks 👍 all looks good to me

2023-08-16 00:53 UTC, inclinedmind approved these changes

2023-08-16 11:20 UTC, codewiththeflowxyz requested changes
Overall I like it and it works well. I found a bit difficult to follow the aggregation process though so maybe we can extract some of the functionality into its own functions with a descriptive name (or simply add some comments describing what you're doing).

The only reason I requested changes is because of the `queryKey` and `<Tr key={...} > ` comments.

2023-08-16 11:20 UTC, codewiththeflowxyz commented on apps/webapp/src/modules/swap/components/SwapHistory.tsx
>                          <Tr key={s.transactionHash}>
This key needs to be updated as transactionHash isn's unique for ungrouped swaps. If you try adding a button that toggles formatted from true to false you'll see the rows start acting weird. This has to be done in combination with the hook's queryKey.

Sth like this works.
`<Tr key={`${s.transactionHash}-${s.id}`}>`

2023-08-16 22:08 UTC, iceanddust commented on apps/webapp/src/modules/swap/components/SwapHistory.tsx
>                          <Tr key={s.transactionHash}>
I think using `s.id` is enough. For both response types, formatted and non-formatted, it should be unique as it consists of the transaction ID + # + a number unique for each sub-transaction

2023-08-16 22:39 UTC, iceanddust commented on apps/webapp/src/modules/swap/components/SwapHistory.tsx
> +  const formatSwapAmount = (input: number): number | string => {
Once that's merged we can apply that function here 👍

2023-08-17 00:53 UTC, inclinedmind commented
looks like this is ready to be merged now?

2023-08-17 07:24 UTC, codewiththeflowxyz approved these changes
Good job 👍 🚀

2023-08-17 17:48 UTC, merged